### PR TITLE
feat: add helpful links tab to student view, other bug fixes

### LINKED ISSUE #602: BUG: Wrong path used for helpful links handler when no favicon is found
**Describe the bug**
The favicon path that gets used by the helpful links handler is for `ul-icon.png` when the name of the image file is `ul-logo.png`. This results in users seeing a broken favicon image when there is no favicon link for the helpful link's url.

**To Reproduce**
1. Go to **Knowledge Center Management > Helpful Links**
2. Click on **Add Link**
3. Add a new helpful link (`Hacker News`, `https://news.ycombinator.com/`, 'Some description`)
4. Notice that the favicon failed to download and use the inspector to see the image path is for `ul-icon.png`.

**Expected behavior**
If the favicon fails to download (I'm not sure why Hacker News does) then it should use the Unlocked Labs icon.

**Screenshots**

image

### LINKED ISSUE #603: BUG: Show Helpful Links Tab in Knowledge Center
**Describe the bug**
When a Resident visits the Knowledge Center, they should see a tab called **Helpful Links** that displays all of the Helpful Links that are marked _Visible_.

Right now, when I visit the Knowledge Center as a Resident, I see three tabs: _Libraries_, _Videos_, and _Favorites_.

**To Reproduce**
1. As an Administrator make sure that there is at least one helpful link that is marked Visible.
2. As a Resident, go to the Knowledge Center.
3. Observe that there is no way to see the Helpful Links.

**Screenshots**
image

### LINKED ISSUE #604: FIX: Add bottom alignment for the Visible/Hidden buttons on Helpful Links
**Describe the bug**
The Visible/Hidden buttons are not vertically aligned when there are Helpful Links that have different content lengths for the description.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by calisio**
## Description of the change

Adds helpful links page, fixes some other small bugs

- **Related issues**: Closes #602 closes #604 closes #603 

## Screenshot(s)
Screenshot 2024-12-23 at 5 07 06 PM

## Additional context

Please include any additional context or information that the reviewer may need to understand the PR.

### CODE REVIEW

**Review by PThorpe92 — APPROVED** [review]

File: frontend/src/Pages/HelpfulLinks.tsx [hunk 1]
```diff
@@ -0,0 +1,49 @@
...
+        mutate: mutateHelpfulFavs,
+        isLoading,
+        error
+    } = useSWR<ServerResponseOne<HelpfulLinkAndSort>, AxiosError>(
+        `/api/helpful-links`
+    );
+    function updateFavorites() {
+        void mutateHelpfulFavs();
+    }
+    useEffect(() => {
```
Comment (PThorpe92) [inline frontend/src/Pages/HelpfulLinks.tsx:24]: can we remove this useEffect?

File: frontend/src/Pages/OpenContent.tsx [hunk 2]
```diff
@@ -10,35 +10,20 @@ export default function OpenContent() {
...
-        videos: { name: OpenContentProviderType.VIDEOS, value: 'Videos' },
-        favorites: { name: 'Favorites', value: 'Favorites' }
-    };
-
+    const currentTabValue = route.pathname.split('/')[2] ?? 'libraries';
+    const tabOptions: Tab[] = [
+        { name: OpenContentProviderType.KIWIX, value: 'libraries' },
+        { name: OpenContentProviderType.VIDEOS, value: 'videos' },
+        { name: OpenContentProviderType.LINKS, value: 'helpful-links' },
+        { name: 'Favorites', value: 'favorites' }
```
Comment (PThorpe92) [inline frontend/src/Pages/OpenContent.tsx:18]: We should probably add 'Favorites' to the enum for consistency

Comment (calisio) [reply frontend/src/Pages/OpenContent.tsx:18]: But its not an open content provider type, so should it be in the enum?

**Review by PThorpe92 — APPROVED** [review]
