### PR TITLE
fix: alter table by changing primary key to be id and add unique contsraint per 721

### LINKED ISSUE #721: BUG: Admins Cannot Feature the Same Library for Multiple Facilities
#### **Describe the bug**  
When an admin tries to feature the same library for multiple facilities, they receive a warning toast:  
*"(!) Library {featured}"*  
Instead of being able to feature the library separately for each facility, the system prevents additional featuring after the first one.  

#### **To Reproduce**  
1. Log in as an **Admin** (SuperAdmin).  
2. Navigate to the **Knowledge Center** for Facility **MVCF**.  
3. Feature a library (e.g., *TED Bees*), indicated by the **yellow flag**.  
4. Change facility view to **Test Facility**.  
5. Attempt to feature the same library again.  
6. Observe the warning toast message:  
   *"(!) Library {featured}"*  

#### **Expected Behavior**  
- Admins should be able to **feature the same library independently for different facilities**.  
- The system should **not** prevent featuring based on prior facility selections.  
- Each facility should have its own **featured content settings**, allowing customization.  

#### **Screenshots**  
https://github.com/user-attachments/assets/a8b5ac2e-5de7-4af5-a8d9-28c90f7eefac

#### **Additional Context**  
- This issue **limits facility-specific customization**, as libraries should be featureable per facility.  
- Check if the issue is **front-end validation only** or if the backend is preventing multiple facility associations.

### PR DESCRIPTION
**Pull request by carddev81**
## Description of the change

Wrote alter SQL script to fix the constraint issues when admins features the same library from multiple facilities.

- **Related issues**: Closes #721

### CODE REVIEW

File: backend/migrations/00031_alter_open_content_favorites_table.sql [hunk 1]
```diff
@@ -0,0 +1,13 @@
...
+ALTER TABLE public.open_content_favorites DROP CONSTRAINT open_content_favorites_pkey, ADD PRIMARY KEY (id);
+
+ALTER TABLE public.open_content_favorites ADD CONSTRAINT unique_open_content_favorite UNIQUE (content_id, open_content_provider_id, user_id, facility_id);
+-- +goose StatementEnd
+
+-- +goose Down
+-- +goose StatementBegin
+ALTER TABLE public.open_content_favorites DROP CONSTRAINT open_content_favorites_pkey, ADD PRIMARY KEY (content_id, open_content_provider_id, user_id);
+
+ALTER TABLE public.open_content_favorites DROP CONSTRAINT unique_open_content_favorite;
```
Comment (PThorpe92) [inline backend/migrations/00031_alter_open_content_favorites_table.sql:12]: for the `Down`, we need to bring this back up

**Review by PThorpe92 — APPROVED** [review]
