### PR TITLE
fix: stop navigation to library viewer when favoriting or unfavoritin…

### LINKED ISSUE #584: BUG: Clicking Favorite/Unfavorite from Trending Content navigates to content
When clicking on the favorite/unfavorite star from the Layer 1 Resident dashboard ("Trending content") the user is navigated to the viewer for the library. If they see the favorite star and it is clickable then clicking on it should perform the desired action. 

https://github.com/user-attachments/assets/d563a0c2-c731-4bde-a5ed-7a5bf4fe6a8d

### PR DESCRIPTION
**Pull request by CK-7vn**
## Description of the change

This is a bug fix that stops navigation to library viewer when a user favorites or unfavorites a library on the trending content page.

- **Related issues**: Closes #584 
## Screenshot(s)

https://www.loom.com/share/defe38f8124246d48a2486826c737946?sid=d438c1e5-7af7-4efe-b64b-f7d31860162e

### CODE REVIEW

File: frontend/src/Components/LibraryCard.tsx [hunk 1]
```diff
@@ -53,18 +56,25 @@ export default function LibraryCard({
             `libraries/${library.id}/favorite`,
             {}
         );
+        if (resp.success) {
+            const isFavorited = library.favorites.length === 0;
+            onFavoriteToggle?.(library.id, isFavorited);
+            if (mutate) void mutate;
```
Comment (PThorpe92) [inline frontend/src/Components/LibraryCard.tsx:62]: since this is an async fn, you can `await` this call to mutate
