### PR TITLE
fix: add button class on  Admin and  Student page, and pencil icon fix

### LINKED ISSUE #619: UX: Different icons & styles used for the Admins and Facility pages
The Edit icon used on the Admins page is different than the one used on the Students page or the Facilities page. Update the Admins page to use the same as seen on the Facilities page. 

The Students & Admin pages need to use the button class on the Add Admin and Add Student button. The button seen on the Facilities page can be used as a reference.

## Facility Page
Image

## Admins Page
Image

### PR DESCRIPTION
**Pull request by CK-7vn**
## Description of the change
Add correct pencil icon in admin management page.
Removed old button classes for add admin and add student, and replaced with the button class.

- **Related issues**: Closes #619 
## Screenshot(s)
image
image

### CODE REVIEW

File: frontend/src/Pages/AdminManagement.tsx [hunk 1]
```diff
@@ -28,6 +27,7 @@ import { AxiosError } from 'axios';
 import API from '@/api/api';
 import ULIComponent from '@/Components/ULIComponent.tsx';
 import { useToast } from '@/Context/ToastCtx';
+import { PencilSquareIcon } from '@heroicons/react/24/solid';
```
Comment (calisio) [inline frontend/src/Pages/AdminManagement.tsx:30]: this should be imported from outline not solid :)

Comment (CK-7vn) [reply frontend/src/Pages/AdminManagement.tsx:30]: Thats why it was a different color! >< I was like "What the ever living???" Searched everywhere, didn't know what was going on. Thank you!

Comment (CK-7vn) [reply frontend/src/Pages/AdminManagement.tsx:30]: All fixed, just pushed over! Thanks!

**Review by calisio — APPROVED** [review]
