### PR TITLE
fix: fix navbar issues when screen is smaller

### LINKED ISSUE #636: Navbar doesn't have slider when it goes off the page
**Describe the bug**
When the screen is minimized, in an elongated fashion, the navbar on the left hand slide is unable to be slid, so you only see the top n amount of options, and are unable to view any others. 
Also, the account name at the bottom of the navbar pops up and out of the navbar. 

**To Reproduce**
1. Go to any page
2. Minimize the screen so that it is elongated in a horizontal fashion
3. Try to scroll down on the page
4. See that the navbar does not move, and that the name of the account pops out of the navbar

**Expected behavior**
No matter the positioning of the screen the navbar should be fully accessible and viewable, and the user name should stay constant. 
**Screenshots**
image
image

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Chrome

### PR DESCRIPTION
**Pull request by CK-7vn**
## Description of the change
Fixes the issue with the Navbar when the window is minimized, it adds scrolling ability in the links, and locks in the icon and user name component at the bottom of the navbar. 

- **Related issues**: Closes #636 

## Screenshot(s)
https://www.loom.com/share/846b8f5815d041868617b0398970d7a5?sid=569953b4-9a98-4336-b27b-6ed8d74d05e1

### CODE REVIEW

File: frontend/src/Components/Navbar.tsx [hunk 1]
```diff
@@ -74,231 +77,204 @@ export default function Navbar({
...
+        <div className="w-60 min-w-[240px] h-screen flex flex-col bg-background">
+            {/* header: pin toggle, brand */}
+            <div className="hidden lg:flex justify-end py-6 mr-4">
                 {isPinned ? (
                     <div
                         className="tooltip tooltip-left"
                         data-tip="Close sidebar"
                     >
                         <ChevronDoubleLeftIcon
-                            className="w-4 opacity-0 group-hover:opacity-100 transition-opacity duration=300 cursor-pointer"
```
Comment (carddev81) [inline frontend/src/Components/Navbar.tsx:85]: I noticed that before the chevron was hidden until user activates the onmouseover on the nav bar and now it is always visible? Making sure this is good to go, also this goes for the other chevron.

File: frontend/src/css/app.css [hunk 2]
```diff
@@ -160,3 +160,11 @@
     position: relative;
     z-index: 10;
 }
+.no-scrollbar::-webkit-scrollbar {
```
Comment (carddev81) [inline frontend/src/css/app.css:163]: You can remove these style classes as these were already defined on lines 83-90 within this file.

**Review by carddev81 — CHANGES_REQUESTED** [review]

**Comment by CK-7vn** [comment]
Changed and forced pushed.

File: frontend/src/Components/Navbar.tsx [hunk 3]
```diff
@@ -103,202 +106,168 @@ export default function Navbar({
...
                                     <li>
-                                        <Link to="/knowledge-center-management/libraries">
+                                        <Link to="/knowledge-center/libraries">
                                             <ULIComponent icon={BookOpenIcon} />
                                             Knowledge Center
                                         </Link>
                                     </li>
-                                )}
-                                <li>
-                                    <Link to="/residents">
```
Comment (carddev81) [inline frontend/src/Components/Navbar.tsx:193]: I missed this, I noticed that the /residents link was removed? It was changed to /students. The Residents link does not forward you to the residents page.

**Review by carddev81 — CHANGES_REQUESTED** [review]

File: frontend/src/Components/Navbar.tsx (hunk 3 above)
Comment (CK-7vn) [reply frontend/src/Components/Navbar.tsx:193]: Hmm....couldve swore I changed that, i'll edit that and take care of it. We're switching the wordage to residents, so I know I meant to. My bad.

Comment (CK-7vn) [reply frontend/src/Components/Navbar.tsx:193]: Done, fixed and pushed.

Comment (carddev81) [reply frontend/src/Components/Navbar.tsx:193]: for real, I could have sworn i tested all the links.  I thought I was tripping for real.

File: frontend/src/Pages/AdminLayer1.tsx [hunk 4]
```diff
@@ -25,7 +25,7 @@ export default function AdminLayer1() {
     const { data: favoritedLibraries } = useSWR<
         ServerResponseMany<OpenContentItem>,
         AxiosError
-    >(`api/libraries?order_by=most_favorited&per_page=5&days=${timeFilter}`);
+    >(`api/libraries?order_by=most_popular&per_page=5&days=${timeFilter}`);
```
Comment (carddev81) [inline frontend/src/Pages/AdminLayer1.tsx:28]: dude, sorry, this isn't related but I think this should be corrected in common.ts since you changed it here...line 813 change most_favorited to most_popular so that it fixes the student filter.

**Review by carddev81 — CHANGES_REQUESTED** [review]

**Review by carddev81 — APPROVED** [review]
