### PR TITLE
Resource management

### LINKED ISSUE #385: BUG: Publishing Changes on Resource Management with no actual changes leaves page in modified state
**Describe the bug**
On the new Resource Management page, when you trigger a modification (e.g., rearranging cards), the UI correctly shows that there are changes to publish. However, if no real changes have been made (such as swapping card 1 with card 2 and then returning them to their original positions), clicking "Publish Changes" does not reset the modified state. The front end continues to show that there are changes to publish, even though no actual modifications were made.

The expected behavior would be to properly reset the UI state of the cards that were modified and disable the Publish Changes button to shower the user that something happened.

**To Reproduce**
View the attachment in [this comment](https://github.com/PThorpe92/UnlockEdv2/pull/5#issuecomment-2361680504) on the original pull request.

1. Go to Resources Management
2. Move the first down a spot.
3. Move that same card back to the top of the list.
4. Click Publish Changes
shots to help explain your problem.

Additional context:
This bug won't exist until the [Revised Resource Management Page issue](https://github.com/orgs/UnlockedLabs/projects/4/views/8?pane=issue&itemId=75855076) has been closed.

### PR DESCRIPTION
**Pull request by MillerSenior**
This pull request implements functionality for the Resource Management page that enhances the user experience both in rearranging resource cards and modifying text fields. In addition to tracking the initial order of the cards to manage the "Publish Changes" button state, we have also updated the Modify Collections section to monitor text changes. When users edit a resource's name or URL, the "Publish Changes" button is activated to indicate modifications. If the user reverts the text back to its original state, the button will automatically deactivate, ensuring that the UI accurately reflects the state of modifications. This cohesive behavior across both card arrangements and text fields provides users with clear visual feedback on their actions, significantly improving the usability of the application. Closes #385

### CODE REVIEW

File: frontend/src/Pages/ResourcesManagement.tsx [hunk 1]
```diff
@@ -181,11 +282,12 @@ export default function ResourcesManagement() {
                             <h3 className="">Resources Preview</h3>
                             <div className="tooltip" data-tip="Add Collection">
                                 <button
-                                    className="btn btn-primary btn-circle btn-xs "
+                                    className="btn btn-primary btn-circle btn-xs"
                                     data-tip="Add Collection"
                                     onClick={() =>
                                         addCollectionModal.current?.showModal()
                                     }
+                                    disabled={!hasMadeModifications()}
```
Comment (jtucholski) [inline frontend/src/Pages/ResourcesManagement.tsx:290]: Is this necessary? I should be able to add new collections without having to make modifications.

File: frontend/src/Pages/ResourcesManagement.tsx [hunk 2]
```diff
@@ -20,55 +19,76 @@ import DeleteForm from '../Components/forms/DeleteForm';
...
     >();
     const [selectedCollectionIndex, setSelectedCollectionIndex] = useState<
         number | undefined
-    >(undefined);
+    >();
+    const [originalLinkValues, setOriginalLinkValues] = useState<
+        Record<number, ResourceLink>
+    >({});
     const [hasDeletedCollection, setHasDeletedCollection] = useState(false);
+    const [, setToast] = useState<ToastProps>({
```
Comment (jtucholski) [inline frontend/src/Pages/ResourcesManagement.tsx:51]: See the other comment I made about using `useToast` in this PR.

File: frontend/src/Pages/ResourcesManagement.tsx [hunk 3]
```diff
@@ -20,55 +19,76 @@ import DeleteForm from '../Components/forms/DeleteForm';
...
+        state: ToastState.null,
+        message: ''
+    });
 
     const addCollectionModal = useRef<HTMLDialogElement>(null);
     const deleteCollectionModal = useRef<HTMLDialogElement>(null);
 
     useEffect(() => {
         if (data) {
+            //eslint-disable-next-line
```
Comment (jtucholski) [inline frontend/src/Pages/ResourcesManagement.tsx:61]: Can we resolve this so `estlint-disable-next-line` isn't necessary? If we need it, please include a comment explaining why we're disabling eslint.

File: frontend/src/Pages/ResourcesManagement.tsx [hunk 4]
```diff
@@ -20,55 +19,76 @@ import DeleteForm from '../Components/forms/DeleteForm';
...
+                (collection: EditableResourceCollection) => ({
+                    ...collection,
+                    id: Math.random(),
+                    isModified: false
+                })
             );
+
             setHasDeletedCollection(false);
             setSelectedCollectionIndex(undefined);
+            //eslint-disable-next-line
```
Comment (jtucholski) [inline frontend/src/Pages/ResourcesManagement.tsx:72]: Can we resolve this so `estlint-disable-next-line` isn't necessary? If we need it, please include a comment explaining why we're disabling eslint.

File: frontend/src/Pages/ResourcesManagement.tsx [hunk 5]
```diff
@@ -20,55 +19,76 @@ import DeleteForm from '../Components/forms/DeleteForm';
...
             setCollectionList(updatedData);
+            //eslint-disable-next-line
```
Comment (jtucholski) [inline frontend/src/Pages/ResourcesManagement.tsx:74]: Can we resolve this so `estlint-disable-next-line` isn't necessary? If we need it, please include a comment explaining why we're disabling eslint.

File: frontend/src/Pages/ResourcesManagement.tsx [hunk 6]
```diff
@@ -147,21 +214,55 @@ export default function ResourcesManagement() {
     };
 
     const updateFinalState = async (e: React.MouseEvent) => {
+        setToast({ state: ToastState.null, message: '' });
```
Comment (jtucholski) [inline frontend/src/Pages/ResourcesManagement.tsx:217]: See the other comment I made about using `useToast` and `toaster`.

File: frontend/src/Pages/ResourcesManagement.tsx [hunk 7]
```diff
@@ -147,21 +214,55 @@ export default function ResourcesManagement() {
...
         });
-        const response = await API.put('left-menu', newCollectionList);
-        if (response.success) {
-            await mutate();
-            toaster('Collections Saved!', ToastState.success);
-        } else {
-            toaster(
-                'All collections must have associated links',
-                ToastState.error
+        try {
```
Comment (jtucholski) [inline frontend/src/Pages/ResourcesManagement.tsx:224]: Can we try and get this to work with `API.put` instead of `axios.put`? We recently refactored a lot of the components and pages to rely on the` API` library to minimize the amount of code spent error checking and validating response status codes.

File: frontend/src/Pages/ResourcesManagement.tsx [hunk 8]
```diff
@@ -147,21 +214,55 @@ export default function ResourcesManagement() {
...
+                }
+
+                setCollectionList(
+                    newCollectionList.map((c) => ({
+                        ...c,
+                        isModified: false
+                    }))
+                );
+            }
+            //eslint-disable-next-line
```
Comment (jtucholski) [inline frontend/src/Pages/ResourcesManagement.tsx:260]: If this needs to stay (it may not with the previous comment) can we remove the `eslint-disable-next-line` or explain why it is necessary?

File: frontend/src/Pages/ResourcesManagement.tsx [hunk 9]
```diff
@@ -217,13 +319,12 @@ export default function ResourcesManagement() {
                     <div className="flex justify-center">
                         <button
                             className="btn btn-primary btn-sm flex items-center justify-center space-x-2 text-white"
-                            onClick={(e) => {
-                                void updateFinalState(e);
-                            }}
+                            //eslint-disable-next-line
```
Comment (jtucholski) [inline frontend/src/Pages/ResourcesManagement.tsx:322]: Can we resolve this so eslint-disable-next-line isn't necessary? If we need it, please include a comment explaining why we need it. 

Look at the previous implementaiton which used `void updateFinalState(e)`. This is consistent with how we do it in the rest of the codebase.

**Review by jtucholski — CHANGES_REQUESTED** [review]
@MillerSenior, I reviewed the code but wasn't able to validate everything was fixed due to a breaking issue. 

Here's a sumamry of the items to resolve:

1. Add Collection button doesn't work until a change gets made. I believe this was added in error. 
2. The toaster was removed from each page during a previous refactor. Look at how it is used in other pages (and the prior version of ResourceManagement) and adopt that pattern.
3. Several `eslint-disable-next-line` comments were introduced. Those were not necessary in the prior version of this page. Look to see if we can move forward without them. If its necessary to add them then include comments explaining why they are necessary.
4. We removed `axios` from most of the pages and created an `API` wrapper library to handle the repetitive work associated with reading the responses and looking for errors.

**Comment by MillerSenior** [comment]
All requested changes address as explained:
1. Add Collection button doesn't work until a change gets made. I believe this was added in error. ✔️

2. The toaster was removed from each page during a previous refactor. Look at how it is used in other pages (and the prior version of ResourceManagement) and adopt that pattern. ✔️

3. Several eslint-disable-next-line comments were introduced. Those were not necessary in the prior version of this page. Look to see if we can move forward without them. If it's necessary to add them, then include comments explaining why they are necessary. ✔️

4. We removed axios from most of the pages and created an API wrapper library to handle the repetitive work associated with reading the responses and looking for errors. ✔️

File: frontend/src/Pages/ResourcesManagement.tsx (hunk 7 above)
Comment (jtucholski) [reply frontend/src/Pages/ResourcesManagement.tsx:214]: @MillerSenior Is there a reason you had to use `axios` instead of `API`? We're trying to make most of our API calls through the `API` library so that we don't have repetitive error-handling code.

File: frontend/src/Pages/ResourcesManagement.tsx [hunk 10]
```diff
@@ -218,12 +301,12 @@ export default function ResourcesManagement() {
                         <button
                             className="btn btn-primary btn-sm flex items-center justify-center space-x-2 text-white"
                             onClick={(e) => {
-                                void updateFinalState(e);
+                                void updateFinalState(e); // Wrap in a void context
```
Comment (jtucholski) [inline frontend/src/Pages/ResourcesManagement.tsx:304]: Can you remove this comment?

**Review by jtucholski — CHANGES_REQUESTED** [review]
@MillerSenior I can't reorder links to take the first position in a collection anymore. I'm almost certain that was working before this bug fix.

**Review by jtucholski — APPROVED** [review]
