### PR TITLE
fix: fix search capitalization issues

### LINKED ISSUE #712: BUG: Search in Knowledge Center (Videos & Helpful Links) is Case-Sensitive
**Describe the bug**
When searching for content in the Videos and Helpful Links tabs of the Knowledge Center, the search fails if capital letters are used. The search only works when entering lowercase letters, making it difficult for users to find content if they enter a title with proper capitalization.

For example:
- Searching for "augustamaine.gov" (lowercase) successfully finds the Helpful Link.
- Searching for "Augustamaine.gov" (capitalized) fails to return any results.

**To Reproduce**
1.  Go to Knowledge Center.
2. Click on either the Videos or Helpful Links tab.
3. Use the search box to search for an existing item by title, entering the title with capital letters.
4. Notice that the search returns no results.
5. Try the same search using lowercase letters only—results appear correctly.

**Expected behavior**
The search should be **case-insensitive**, meaning that results should appear regardless of whether the user enters uppercase or lowercase letters.

**Screenshots**
Image
Image

**Additional context**
- This issue affects both the Videos and Helpful Links tabs but does not seem to impact the Libraries tab.
- The search functionality should be updated to be case-insensitive to improve usability.
- This may require adjusting the search query to normalize case before filtering results.

### LINKED ISSUE #713: BUG: Missing Search in Knowledge Center (Resident View) for Helpful Links and Favorites
**Description:**  
Right now, the **Helpful Links** page in the Knowledge Center (Admin) includes a search box, but the **Residents’ version does not**. This makes it difficult for Residents to find specific Helpful Links when the list is long.  

Similarly, the **Favorites tab** in the Knowledge Center (Residents) is missing a search box. If a Resident has a large list of favorited content, they have no easy way to find a specific item.  

**Expected Behavior:**  
- Add a search box to the **Residents' Helpful Links** page to make finding links easier.  
- Add a search box to the **Residents' Favorites tab** to help them quickly locate favorited content.

### PR DESCRIPTION
**Pull request by CK-7vn**
## Description of the change
Fixes the issue with capitalization in the Helpful Links, and Videos. You can now search with capitalized words and or non-capitalized words, capitalization is irrelevant. Also adds missing search and order by for the student side of helpful links, and favorites. 

- **Related issues**: Closes #713  Closes #712 

## Screenshot(s)
image
image
image
image
image
image

### CODE REVIEW

File: backend/src/database/open_content.go [hunk 1]
```diff
@@ -138,104 +140,159 @@ func (db *DB) GetUserFavoriteGroupings(userID uint) ([]models.OpenContentItem, e
...
 }
 
-func (db *DB) GetUserFavorites(userID uint, page, perPage int) (int64, []models.OpenContentItem, error) {
+func (db *DB) GetUserFavorites(userID uint, page, perPage int, orderBy, search string) (int64, []models.OpenContentItem, error) {
+	var libSearchCond, videoSearchCond, hlSearchCond string
+	var searchTerm string
+
+	if search != "" {
+		searchTerm = "%" + strings.ToLower(search) + "%"
+		libSearchCond = "AND lib.title ILIKE ?"
```
Comment (PThorpe92) [inline backend/src/database/open_content.go:149]: I think we should use `AND LOWER(x.title) LIKE ?` because sqlite (tests) don't support ILIKE. should also be more performant

File: backend/src/database/open_content.go [hunk 2]
```diff
@@ -138,104 +140,159 @@ func (db *DB) GetUserFavoriteGroupings(userID uint) ([]models.OpenContentItem, e
...
+		orderBy = "created_at DESC"
+	case "created_at ASC":
+		orderBy = "created_at ASC"
+	case "most_popular":
+		orderBy = "popularity_score DESC"
+	default:
+		orderBy = "created_at DESC"
+	}
+
+	countQuery := fmt.Sprintf(`SELECT COUNT(*) FROM (
```
Comment (PThorpe92) [inline backend/src/database/open_content.go:174]: We are interpolating strings here into queries, we should make sure these are properly santiized first

File: backend/src/database/open_content.go [hunk 3]
```diff
@@ -138,104 +140,156 @@ func (db *DB) GetUserFavoriteGroupings(userID uint) ([]models.OpenContentItem, e
...
+		hlSearchCond = "AND LOWER(hl.title) LIKE ?"
+	}
+
+	countArgs := []interface{}{userID}
+	if search != "" {
+		countArgs = append(countArgs, searchTerm)
+	}
+
+	var allowedOrderBy = map[string]string{
+		"title ASC":       "title ASC",
```
Comment (PThorpe92) [inline backend/src/database/open_content.go:160]: the values here can just be booleans or better `struct{}` for zero size, we just want to have both sets we are comparing be trimmed and lower case so we don't mismatch

**Review by PThorpe92 — APPROVED** [review]
